export const CONVERSATION_CREATE_REQUEST = 'CONVERSATION_CREATE_REQUEST'
export const CONVERSATION_CREATE_SUCCESS = 'CONVERSATION_CREATE_SUCCESS'
export const CONVERSATION_CREATE_FAIL = 'CONVERSATION_CREATE_FAIL'

export const CONVERSATIONS_LIST_REQUEST = 'CONVERSATIONS_LIST_REQUEST'
export const CONVERSATIONS_LIST_SUCCESS = 'CONVERSATIONS_LIST_SUCCESS'
export const CONVERSATIONS_LIST_FAIL = 'CONVERSATIONS_LIST_FAIL'

export const CONVERSATION_DETAIL_REQUEST = 'CONVERSATION_DETAIL_REQUEST'
export const CONVERSATION_DETAIL_SUCCESS = 'CONVERSATION_DETAIL_SUCCESS'
export const CONVERSATION_DETAIL_FAIL = 'CONVERSATION_DETAIL_FAIL'
